package co.algorand.passkeyautofill.credentials

import java.security.MessageDigest
import java.security.Security
import java.security.Signature
import java.security.interfaces.ECPrivateKey
import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Vectors from test-vectors/site-credential-vectors.json, generated by running the
 * iOS provider's derivation (SiteCredentialDerivation, CryptoKit). If these fail,
 * a site passkey created through Akita on Android will not match iOS.
 */
class SiteCredentialDerivationTest {
    private data class Vector(
        val name: String,
        val rpId: String,
        val userNameUtf8Hex: String,
        val handleUtf8Hex: String,
        val privateKeyHex: String,
        val publicKeySpkiHex: String,
        val credentialIdHex: String,
    )

    private val rootHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"

    private val vectors = listOf(
        Vector(
            name = "ascii-mixed-case-email",
            rpId = "example.com",
            userNameUtf8Hex = "416c696365404578616d706c652e4f5247",
            handleUtf8Hex = "616c696365406578616d706c652e6f7267",
            privateKeyHex = "24df793974d87f571931af2c761eafb24bf95946557d4c4ba0ebcdd2c25b0c49",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d03010703420004b3c9654644c642e6b875b24e3dcffbdc8e72b383684c9a24cab7052aff166d6c5ec77c37a77c31024c178ab4361c0655b0a06df8e1d00e061a9a39d46996441e",
            credentialIdHex = "96b5f7ecb740704b632940dae5de9b325fc6983d2fc7cec10852556f1c803314",
        ),
        Vector(
            name = "ascii-lowercase",
            rpId = "webauthn.io",
            userNameUtf8Hex = "626f62",
            handleUtf8Hex = "626f62",
            privateKeyHex = "6d38ca5a32a4bf9874b33367d4ec6e6905ff80739def186a411b72eeca1a65c9",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d03010703420004a2ee6d48066abe6ea7e4ee74c156b892a416fec1ff4ad776484778c856e57bec5dd1e0ea9b5f1ce5b3de11e483beb71c32eba34ca3b6001b59573e7dc135357d",
            credentialIdHex = "95b02d303da294be517a7d19064ae6e181968b93d9dcd32e6870c9e96472358b",
        ),
        Vector(
            name = "greek-final-sigma",
            rpId = "example.com",
            userNameUtf8Hex = "ce9fce94cea5cea3cea3ce95cea5cea3",
            handleUtf8Hex = "cebfceb4cf85cf83cf83ceb5cf85cf83",
            privateKeyHex = "ff32a3a67c9ab473d68995c60e08c319e79b43c620a230d90fddbbc367008dee",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d0301070342000480b9ee8f3bb94e3f545c83223aaf6332701116412a3dc7a57c5ec6ee4451768f5821d2f1701aa3da64e9ebfa0ea46501203649e82fca4f8badb1048a80fc90bf",
            credentialIdHex = "2643edd0a5f0de728e8fad0243fe4316ac7a3638d30bc9237eea6bdfa536cb16",
        ),
        Vector(
            name = "greek-sigma-before-digit",
            rpId = "example.com",
            userNameUtf8Hex = "ce91cea331ce92",
            handleUtf8Hex = "ceb1cf8331ceb2",
            privateKeyHex = "ed4a314dc77b759511b12d5a6fe06c1ed3a0befe9767d065f50eb27ea165a857",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d030107034200043c8ed0b414db7a666725ddf9cf58f309ed05ccb71315d13c315c86e5d99bf5c1219a59bd521e4c1823d3247d64f245868f4557c9183d7c4913dcb4c3b868e102",
            credentialIdHex = "c12ec9532f60350d70a53a25322aef466bd367bc56b962a437a2babb0b34bcbb",
        ),
        Vector(
            name = "dotted-capital-i",
            rpId = "example.com",
            userNameUtf8Hex = "c4b07374616e62756c",
            handleUtf8Hex = "69cc877374616e62756c",
            privateKeyHex = "5b81c099fb26f158faf8886e7ff5ca35eaea75afe64f4ad98095e7c8a2253e83",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d030107034200048182a81cb083530036bd73417c175e152f81530af89d5d850008f52a706e4edb420faecd4db6dea3d3db62cd558a6ec657c65a0f27a736d5aa9c2d33c19b861e",
            credentialIdHex = "062ebc9ab2fb3a3c5e5f6a34d835fda81c999ceee1e13389da2ff45f3fe05d4a",
        ),
        Vector(
            name = "sharp-s",
            rpId = "accounts.example.org",
            userNameUtf8Hex = "5354524153534520c39f",
            handleUtf8Hex = "7374726173736520c39f",
            privateKeyHex = "b23a4a358d392188edb145b0dd760dfceb72e488ad15001ca053a6e50a7233ad",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d030107034200047b7899194ab9ff03aee514a8dd4b358872f69c0d96bc81e2a459586a70ccd5cf05cdc5dc88ad3371685621037458e8bccb262537fa27903449c7248ea3374731",
            credentialIdHex = "62c6a4478a78011389665b3321c2c4d34f96577a71c3cd1b3ed7a2d743855dce",
        ),
        Vector(
            name = "titlecase-letter",
            rpId = "example.com",
            userNameUtf8Hex = "c785656d616c",
            handleUtf8Hex = "c786656d616c",
            privateKeyHex = "165fa5b417eac99cb73af7f1f2db42e77fdf1e83dd1be9938033a271bc86a0d0",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d03010703420004c43f548105d25fdf9603cfc1b63dbc40b3f0c3d83e161671587e84f0fbb93ca15ef247e713ba0d77aa79ed63c35100b61be624f2ea88daa6657067562aab6d08",
            credentialIdHex = "bd74c4e12256b4bdae9919ec1b7f8c84324c229aeff02e39a82aa49197365a50",
        ),
        Vector(
            name = "akita-connect",
            rpId = "akita.community",
            userNameUtf8Hex = "416b6974612048797065727370616365",
            handleUtf8Hex = "616b6974612068797065727370616365",
            privateKeyHex = "54c68f64cf825cdde82c505c053e919a1b7f1121d05817468753d4c7c944ffe2",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d0301070342000470172f572c768caa47c49ccf9d4e85aa1bcf2d6073da3c9d2295c1dd76bd7510adcc04a97257d095b2eac800c303dac9bcb3fa9caea9aeb37060dec50941566f",
            credentialIdHex = "56454218bc54769b88831804eb8c7987e79e10ccd0289eaa2f2c93f62411b474",
        ),
        Vector(
            name = "empty-name",
            rpId = "example.com",
            userNameUtf8Hex = "",
            handleUtf8Hex = "",
            privateKeyHex = "98b264964a071b369a55e138f1a19417449e3690c9eef7d2c3453d318a138b43",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d03010703420004a709a64f947be04ca177c46ba8615b35dcff16b88306e3b383e219b9fb30f88b764bff4f5997861d2764507ae7b0908724c275931bc11b0519e1631fcb2a0607",
            credentialIdHex = "4e78315072026c9753027540294f027ad80b506a5a4f1e3b75db94a0720fda57",
        ),
    )

    @Test
    fun handleMatchesIos() {
        for (v in vectors) {
            val userName = String(v.userNameUtf8Hex.hexToBytes(), Charsets.UTF_8)
            val handle = SiteCredentialDerivation.handleForUserName(userName)
            assertEquals(v.name, v.handleUtf8Hex, handle.toByteArray(Charsets.UTF_8).toHex())
        }
    }

    @Test
    fun derivedKeysMatchIos() {
        val root = rootHex.hexToBytes()
        for (v in vectors) {
            val handle = SiteCredentialDerivation.handleForUserName(String(v.userNameUtf8Hex.hexToBytes(), Charsets.UTF_8))
            val keyPair = SiteCredentialDerivation.deriveKeyPair(root, v.rpId, handle)
            assertEquals(v.name, v.privateKeyHex, (keyPair.private as ECPrivateKey).s.toString(16).padStart(64, '0'))
            assertEquals(v.name, v.publicKeySpkiHex, keyPair.public.encoded.toHex())
            assertEquals(v.name, v.credentialIdHex, MessageDigest.getInstance("SHA-256").digest(keyPair.public.encoded).toHex())
        }
    }

    @Test
    fun derivedKeysSignWithBouncyCastleLikeTheProvider() {
        // CredentialRepository signs through dP256's signWithDomainSpecificKeyPair, which uses
        // Signature.getInstance("SHA256withECDSA", "BC") on the stored ECPrivateKey.
        if (Security.getProvider("BC") == null) Security.addProvider(BouncyCastleProvider())
        val keyPair = SiteCredentialDerivation.deriveKeyPair(rootHex.hexToBytes(), "example.com", "alice")
        val payload = "authenticatorData-and-clientDataHash".toByteArray()
        val signature = Signature.getInstance("SHA256withECDSA", "BC").run {
            initSign(keyPair.private)
            update(payload)
            sign()
        }
        val verified = Signature.getInstance("SHA256withECDSA", "BC").run {
            initVerify(keyPair.public)
            update(payload)
            verify(signature)
        }
        assertTrue(verified)
    }

    private fun String.hexToBytes(): ByteArray = chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }
}
