package co.algorand.passkeyautofill.credentials

import java.security.MessageDigest
import java.security.Security
import java.security.Signature
import java.security.interfaces.ECPrivateKey
import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Vectors generated by running the iOS provider's derivation code
 * (CredentialProviderViewController.domainSpecificKeyPair with CryptoKit). If these fail,
 * a site passkey created through Akita on Android will not match the same passkey on iOS.
 */
class SiteCredentialDerivationTest {
    private data class Vector(
        val name: String,
        val rpId: String,
        val userIdHex: String,
        val canonicalUserHandleUtf8Hex: String,
        val counter: Int,
        val privateKeyHex: String,
        val publicKeySpkiHex: String,
        val credentialIdHex: String,
    )

    private val rootHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"

    private val vectors = listOf(
        Vector(
            name = "ascii-mixed-case",
            rpId = "example.com",
            userIdHex = "4162432d557365725f3432",
            canonicalUserHandleUtf8Hex = "6162632d757365725f3432",
            counter = 0,
            privateKeyHex = "50b7bb36d74f67e7649a52df02c5dc3aa0442450f61e4e44438ccce4c3de780b",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d030107034200043a572a62b17561ed0d9e47c72f139bef48e0a3fc7b0274c56f1b593048a6a4fe30a457f0bfd777fb5079aaf090509db9cd090e4237ffab88aa12f2d545787ab0",
            credentialIdHex = "6dd7f8fd659947a74b0c5f462af80aaa84366951bca6399f61c02e4a7d7e7ca6",
        ),
        Vector(
            name = "random-bytes-not-utf8",
            rpId = "webauthn.io",
            userIdHex = "ff00a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e",
            canonicalUserHandleUtf8Hex = "5f776368737370753566796867636b3673317874666f2d716f626c64316f7832627867706f6b7463627834",
            counter = 0,
            privateKeyHex = "fe0887892041c68f85a71fac51051535f8668cab54a780ebfe461455db10baf5",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d0301070342000419922177bfe41af56df738d65a5b718d177f5a3039bcacb1fe09629e996cec5b40e64bb6b6011ae259051dc5f66b918cf4d4f4e980e2818a425edea526d7d19f",
            credentialIdHex = "493eadeddeebbd022faeb885c62330d5bbccab3e51a9625646fe3a032ee02e92",
        ),
        Vector(
            name = "akita-connect-random-32",
            rpId = "akita.community",
            userIdHex = "c3a9e1f28d0b4c5a6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5",
            canonicalUserHandleUtf8Hex = "77366e68386f306c74667075663463726f7270653165623363626b716f307864626e2d616b616b7a786e75",
            counter = 0,
            privateKeyHex = "bd4f284cc1deb9f43c242447d961201fc734451ff402fce81a9fd60962ade0d0",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d03010703420004faae08606bb951dc892909b31d9dc5606617edb311f775ba35a5b5ab9a2b0b7cb598c1ce36c734ba1a628f9ea36691175761b0312ba82eb8c8ef95decfb60e6c",
            credentialIdHex = "e4eff9ccee93a7a4914596db2679530dd2101f950e8966ea070fa94568d9613d",
        ),
        Vector(
            name = "utf8-with-bom",
            rpId = "example.com",
            userIdHex = "efbbbf616263",
            canonicalUserHandleUtf8Hex = "616263",
            counter = 0,
            privateKeyHex = "683e2053fbeb598618cd89b0ca5d1ed8022b1118e019f24b0516dfe831451142",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d030107034200044df07aed10bc57960b955b18cceaebcca9495967bc1a8aedfd87c2f238557e0ce6721e76d592c2b30b2d2cf44c40304eeee85b5c70c58c7da675889a2db00448",
            credentialIdHex = "645530380f1b4db67c8162b3303bccd417975b6261361e8ddac77afee69fc679",
        ),
        Vector(
            name = "non-ascii-case",
            rpId = "example.com",
            userIdHex = "c384c3962dcea3cea32dc4b02dc39f",
            canonicalUserHandleUtf8Hex = "c3a4c3b62dcf83cf832d69cc872dc39f",
            counter = 0,
            privateKeyHex = "ad6fccd833106a4b13e8ed2b64e045d1b1ffe4451c0cf0126fb156944f7cfd11",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d030107034200047644fd2ad7a8912f167d77ae6b767195e112c92b6c241bc10fb6aefdd76a2d4fb9e4fffd4795219c67752cfa835b67c878f2cd64f0a72e8dae62142daf5d4b2a",
            credentialIdHex = "3f827219c0f5c4c0ae55c48ee4623c5a0d8cc5b62edd3a9e669f4fafd1a11a5c",
        ),
        Vector(
            name = "nul-bytes",
            rpId = "example.com",
            userIdHex = "00000000000000000000000000000000",
            canonicalUserHandleUtf8Hex = "00000000000000000000000000000000",
            counter = 0,
            privateKeyHex = "481ea8152ded7f3305ff503e6d7b72ec05bb6b4561f5b0896f8841297c4a4733",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d030107034200041e07be96afc4e18b4cc93b0a609429db96c67b68731d3bc393954123df67442a47a9db9a27c7e38f7bd38ef7c54d851ef6a602fc780c06a696ff6290d59ac07e",
            credentialIdHex = "7204b8a4f2d6ed48295771f538436713fe68b031f4389db310d062b590445ce4",
        ),
        Vector(
            name = "uppercase-email",
            rpId = "accounts.example.org",
            userIdHex = "416c696365404578616d706c652e4f5247",
            canonicalUserHandleUtf8Hex = "616c696365406578616d706c652e6f7267",
            counter = 0,
            privateKeyHex = "a492ac05b8ea7fdff2453ef351847e57e62eca76ff682da26e2d6bdeb3cb537d",
            publicKeySpkiHex = "3059301306072a8648ce3d020106082a8648ce3d03010703420004ad684e0bf110dd59d341c4780fe73adf2aa74b67f705bf26e8948e0993fd6d3b191b12a818132dd7686549a61fb12d96fc86f473c9f6c47fc9523ccf9ebd4fb1",
            credentialIdHex = "217377a187832cfbd7fdff89c92f66d8fcd20feb86dec9295090cdb7fa9b6103",
        ),
    )

    @Test
    fun canonicalUserHandleMatchesIos() {
        for (v in vectors) {
            val handle = SiteCredentialDerivation.canonicalUserHandle(v.userIdHex.hexToBytes())
            assertEquals(v.name, v.canonicalUserHandleUtf8Hex, handle.toByteArray(Charsets.UTF_8).toHex())
        }
    }

    @Test
    fun derivedKeysMatchIos() {
        val root = rootHex.hexToBytes()
        for (v in vectors) {
            val handle = SiteCredentialDerivation.canonicalUserHandle(v.userIdHex.hexToBytes())
            val (d, counter) = SiteCredentialDerivation.derivePrivateScalar(root, v.rpId, handle)
            assertEquals(v.name, v.counter, counter)
            assertEquals(v.name, v.privateKeyHex, d.toByteArray().takeLast(32).toByteArray().toHex().padStart(64, '0'))

            val keyPair = SiteCredentialDerivation.deriveKeyPair(root, v.rpId, handle)
            assertEquals(v.name, v.privateKeyHex, (keyPair.private as ECPrivateKey).s.toString(16).padStart(64, '0'))
            assertEquals(v.name, v.publicKeySpkiHex, keyPair.public.encoded.toHex())
            val credentialId = MessageDigest.getInstance("SHA-256").digest(keyPair.public.encoded)
            assertEquals(v.name, v.credentialIdHex, credentialId.toHex())
        }
    }

    @Test
    fun derivedKeysSignWithBouncyCastleLikeTheProvider() {
        // CredentialRepository signs through dP256's signWithDomainSpecificKeyPair, which uses
        // Signature.getInstance("SHA256withECDSA", "BC") on the stored ECPrivateKey.
        if (Security.getProvider("BC") == null) Security.addProvider(BouncyCastleProvider())
        val keyPair = SiteCredentialDerivation.deriveKeyPair(rootHex.hexToBytes(), "example.com", "abc")
        val payload = "authenticatorData-and-clientDataHash".toByteArray()
        val signature = Signature.getInstance("SHA256withECDSA", "BC").run {
            initSign(keyPair.private)
            update(payload)
            sign()
        }
        val verified = Signature.getInstance("SHA256withECDSA", "BC").run {
            initVerify(keyPair.public)
            update(payload)
            verify(signature)
        }
        assertTrue(verified)
    }

    private fun String.hexToBytes(): ByteArray = chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }
}
